# Generated by Django 4.2 on 2023-04-11 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.IntegerField(unique=True)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_start", models.DateTimeField()),
                ("reservation_end", models.DateTimeField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("COM", "PAYMENT_COMPLETE"),
                            ("INC", "PAYMENT_INCOMPLETE"),
                            ("PAR", "PAYMENT_PARTIALLY_COMPLETE"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
